# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# ***************************************************************************
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mauricio Antelis
email: mauricio.antelis@gmail.com
description: 
twitter_username: 
github_username: 
minimal_mistakes_skin: aqua # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false

# ***************************************************************************
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# ***************************************************************************
include:
  - _pages

# ***************************************************************************
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# ***************************************************************************
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ***************************************************************************
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# ***************************************************************************
# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# ***************************************************************************
# Site Author
author:
  name             : # "Mauricio Antelis"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Professor-Researher, Computer Science Department, Tecnologico de Monterrey."
  location         : "Monterrey, NL, Mexico"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mauricio.antelis@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mauricioantelis.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mauricioantelis"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-3377-0813"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/javier-m-antelis/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Javier-Antelis/"      
#    - label: "CV"
#      url: "https://mauricioantelis.github.io/assets/CV2023.pdf"

# ***************************************************************************
# Site Footer
#footer:
#  links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope-square"
#      #url: "mailto:mauricio.antelis@gmail.com"
#    - label: "LinkedIn"
#      icon: "fab fa-fw fa-linkedin-in"
#      #url: "https://www.linkedin.com/in/javier-m-antelis/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      #url:

# ***************************************************************************
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true

# ***************************************************************************
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
